/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DataRouteImport } from './routes/data'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FflLicenseIdRouteImport } from './routes/ffl.$licenseId'
import { Route as ApiPublicAtfListRouteImport } from './routes/api/public/atf-list'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FflLicenseIdRoute = FflLicenseIdRouteImport.update({
  id: '/ffl/$licenseId',
  path: '/ffl/$licenseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAtfListRoute = ApiPublicAtfListRouteImport.update({
  id: '/api/public/atf-list',
  path: '/api/public/atf-list',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/data': typeof DataRoute
  '/history': typeof HistoryRoute
  '/results': typeof ResultsRoute
  '/ffl/$licenseId': typeof FflLicenseIdRoute
  '/api/public/atf-list': typeof ApiPublicAtfListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/data': typeof DataRoute
  '/history': typeof HistoryRoute
  '/results': typeof ResultsRoute
  '/ffl/$licenseId': typeof FflLicenseIdRoute
  '/api/public/atf-list': typeof ApiPublicAtfListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/data': typeof DataRoute
  '/history': typeof HistoryRoute
  '/results': typeof ResultsRoute
  '/ffl/$licenseId': typeof FflLicenseIdRoute
  '/api/public/atf-list': typeof ApiPublicAtfListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/data'
    | '/history'
    | '/results'
    | '/ffl/$licenseId'
    | '/api/public/atf-list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/data'
    | '/history'
    | '/results'
    | '/ffl/$licenseId'
    | '/api/public/atf-list'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/data'
    | '/history'
    | '/results'
    | '/ffl/$licenseId'
    | '/api/public/atf-list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DataRoute: typeof DataRoute
  HistoryRoute: typeof HistoryRoute
  ResultsRoute: typeof ResultsRoute
  FflLicenseIdRoute: typeof FflLicenseIdRoute
  ApiPublicAtfListRoute: typeof ApiPublicAtfListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ffl/$licenseId': {
      id: '/ffl/$licenseId'
      path: '/ffl/$licenseId'
      fullPath: '/ffl/$licenseId'
      preLoaderRoute: typeof FflLicenseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/atf-list': {
      id: '/api/public/atf-list'
      path: '/api/public/atf-list'
      fullPath: '/api/public/atf-list'
      preLoaderRoute: typeof ApiPublicAtfListRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DataRoute: DataRoute,
  HistoryRoute: HistoryRoute,
  ResultsRoute: ResultsRoute,
  FflLicenseIdRoute: FflLicenseIdRoute,
  ApiPublicAtfListRoute: ApiPublicAtfListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
